#ifndef CONSTS_H
#define CONSTS_H

#define YEAR_COL 0
#define REGION_COL 1
#define NAME_MAX_LEN 200
#define MAX_CSVLINE_LENGTH 2048
#define MAX_PATH_LEN 4096
#define DEFAULT_ROW_NUM 32


// plot constants
#define PLOT_WINDOW_WIDTH 800
#define PLOT_WINDOW_HEIGHT 600
#define PLOT_RIGHT_MARGIN 80
#define PLOT_LEFT_MARGIN 60
#define MARGIN 30
#define AXLE_MARGIN 15
#define MARK_DENSITY_X 2
#define MARK_COUNT_Y 7
#define MARK_LEN 5
#define MARK_TEXT_SHIFT_X 15
#define MARK_TEXT_SHIFT_Y 15
#define POINT_RADIUS 4
#define TEXT_SHIFT_X 20
#define TEXT_SHIFT_Y 3

#endif // CONSTS_H
