#ifndef CONSTS_H
#define CONSTS_H

#define YEAR_COL 0
#define REGION_COL 1
#define NAME_MAX_LEN 200
#define MAX_CSVLINE_LENGTH 2048
#define MAX_PATH_LEN 4096
#define DEFAULT_ROW_NUM 32

#define PLOT_WINDOW_WIDTH 800
#define PLOT_WINDOW_HEIGHT 600

#endif // CONSTS_H
